### PR TITLE
Set up responsive layout for Candid UI authorization panel

### PR DESCRIPTION
**Pull request by rvanasa**
This PR adjusts the style of the new auth UI. I also replaced the "infinity" logo with the monochromatic "astronaut" for consistency with Internet Identity login buttons in other DFINITY dapps. 

Context: #475.

> Desktop screen width:

image

> Tablet screen width:

image

> Mobile screen width:

image

### CODE REVIEW

**Comment by Web3NL** [comment]
May I ask, how do you guys locally develop this UI? 
(I need to be able see the styling when in the iframe inside Motoko Playground) 

@rvanasa only looking at the css, it looks like its (almost) done? Can I improve anything or should I go on to documenting this feature in portal?

**Comment by chenyan-dfinity** [comment]
Two ways: 1) if you open the UI on a separate window and reduce the width of the browser window, the UI will change to its mini form; 2) To test it in the playground, update this line https://github.com/dfinity/motoko-playground/blob/main/src/config/actor.js#L38 to be the new Candid UI canister id.

**Comment by rvanasa** [comment]
> only looking at the css, it looks like its (almost) done?

I'll take care of the responsive layout. :)

**Review by chenyan-dfinity — APPROVED** [review]

**Comment by Web3NL** [comment]
> > only looking at the css, it looks like its (almost) done?
> 
> I'll take care of the responsive layout. :)

Great! 

I will make sure this is properly documented.

**Pull request merged**
