### PR TITLE
adds CandidType for Uuid behind Uuid feature flag

### PR DESCRIPTION
**Pull request by lunchspider**
**Overview**
Why do we need this feature? What are we trying to accomplish?
Adds CandidType impl for Uuid

**Requirements**
What requirements are necessary to consider this problem solved?
Uuid are widely used as a Ids. This makes it easier to work with

### CODE REVIEW

**Comment by chenyan-dfinity** [comment]
Can this be done outside of candid crate, e.g., wrapping a newtype for `Uuid` and implement `CandidType` for the newtype in the user crate?

**Comment by lunchspider** [comment]
yeah but then this wouldn't work
```
#[derive(CandidType)]
struct SomeStruct{
 id : Uuid
}
```
`Uuid` is widely used everywhere creating a wrapper element for uuid means user will have to implement every trait on it..
which becomes very hard if working with 2-3 external crate, primarily databases.

**Comment by chenyan-dfinity** [comment]
Right, you cannot `derive`, but you can manually `impl CandidType for SomeStruct`. Then any structure using `SomeStruct` can derive `CandidType`. This can be a separate crate that other projects depend on.

Reasons for not including this in `candid` crate:

* The above workaround exists and is a common pattern in Rust.
* Avoids unnecessary dependency. Not every project using Candid requires a UUID library. It's reasonable to impl structures from `std`, but not beyond that. 
* You can hide the dependency under a feature flag, but it bloats the library. There are also legal concerns for which license we can include as the transitive dependency.
* Even for a specific feature, we don't want to decide which implementation is the canonical one by including a particular crate in Cargo.toml.

Overall, I think impl a trait for an external crate is an anti-pattern in Rust. We should use newtypes whenever possible.

**Comment by lunchspider** [comment]
ohk, got you!
Thanks

**Pull request closed without merging**
